### PR TITLE
adds settings for a  global config

### PR DESCRIPTION
**Pull request by bananenmannfrau**
Allows for a config that can be set globally for all .less files. I was not able to figure out a good test scenario as the ```__dirname``` and ```path.dirname(filePath)``` are equal and such the global config file is loaded as a local one.

If you could point me in the right direction, im happy to add the testing :)

### CODE REVIEW

**Comment by kokarn** [comment]
This looks very useful. I'd really like to have it tested however... Any toughts @jwilsson ?

**Comment by jwilsson** [comment]
Hi,
Thanks for working on this!

I do have some thoughts, does it really make sense to put the configuration inside the package's installation directory? I don't know if this file might be deleted on each update (I'm thinking that Atom might delete the whole directory when updating, but I don't know).

Two suggestions that I got:
1. We change the `globalConfig` option to instead point to a file anywhere on disk to be globally used.
2. We change the current behaviour of always looking in the project folder and instead let `lesshint` find the `.lesshintrc` itself, starting from the project folder and working its way up the the user root. 
It does this already when no config file is passed, starting from `process.cwd()` and working it's way up. I'll admit this is poorly documented, though.

The second approach will probably require a change in the main `lesshint` project as well since I'm guessing we would need to point it to a path where it should start looking, cause I think `process.cwd()` will be incorrect. I've been thinking about doing this anyway so I'll open an issue about that straight away.

Let me know what you think!

**Comment by bananenmannfrau** [comment]
I like the option to specify a file. I should have some time this week to update this PR.

**Comment by bananenmannfrau** [comment]
I have updated the PR. Now its possible to specify a directory where the global file is located.
@kokarn @jwilsson

**Comment by jwilsson** [comment]
`os.homedir()` is probably better (no extra dependencies) but other than that I'm good.

**Comment by jwilsson** [comment]
Thanks for contributing @bananenmannfrau! 🎉 

I'll tag a new version later today.

**Pull request merged**
